# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Shady Nawara
email: shady.nawara@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  I focus on designing reliable systems that solve real-world problems,
  specializing in 3D computation and visualization. I enjoy tinkering with
  hardware projects and reverse engineering.

taglong: Architect, Developer, Always Learning.
tagshort: Shady Nawara

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://shadynawara.com" # the base hostname & protocol for your site, e.g. http://example.com

social:
  github: shadynawara
  gitlab: shadynawara
  linkedin: shadynawara
  x: shadynawara

# author settings
author:
  name: Shady Nawara
  email: shady.nawara@outlook.com
photo: assets/photo.gif
address: Austin, TX
phone: +1 612 417 5569

# Build settings
theme: cvless
plugins:
  - jekyll-feed

google_analytics: G-V5GFHPXVN9

permalink: pretty
exclude:
  - docker-compose.yml
  - LICENSE
  - README.md
